wso2-extensions/identity-auth-organization-login

components/org.wso2.carbon.identity.application.authenticator.organization.login/pom.xml, pom.xml
=> Bump kernel to 4.7.0

pom.xml
=> Change identity.outbound.auth.oidc.import upper bound

pom.xml
=> Bump oauth version and remove unneccessary properties in pom file

components/org.wso2.carbon.identity.application.authenticator.organization.login/src/main/java/org/wso2/carbon/identity/application/authenticator/organization/login/OrganizationAuthenticator.java, components/org.wso2.carbon.identity.application.authenticator.organization.login/src/main/java/org/wso2/carbon/identity/application/authenticator/organization/login/constant/AuthenticatorConstants.java
=> Update token & authorize endpoints for fedarated authentication by organization routed paths

components/org.wso2.carbon.identity.application.authenticator.organization.login/pom.xml, pom.xml
dependency changes due to moving org mgt service to org mgt core
version bump
Merge after:
https://github.com/wso2-extensions/identity-organization-management/pull/136
https://github.com/wso2-extensions/identity-inbound-auth-oauth/pull/1898
=> update dep due to moving org mgt service to core

components/org.wso2.carbon.identity.application.authenticator.organization.login/src/main/java/org/wso2/carbon/identity/application/authenticator/organization/login/OrganizationAuthenticator.java, components/org.wso2.carbon.identity.application.authenticator.organization.login/src/main/java/org/wso2/carbon/identity/application/authenticator/organization/login/constant/AuthenticatorConstants.java
=> Add federated_org user attribute after successful organization login flow

components/org.wso2.carbon.identity.application.authenticator.organization.login/src/main/java/org/wso2/carbon/identity/application/authenticator/organization/login/OrganizationAuthenticator.java, components/org.wso2.carbon.identity.application.authenticator.organization.login/src/main/java/org/wso2/carbon/identity/application/authenticator/organization/login/constant/AuthenticatorConstants.java
=> Update user organization claim

pom.xml
=> Bump auth version

components/org.wso2.carbon.identity.application.authenticator.organization.login/src/main/java/org/wso2/carbon/identity/application/authenticator/organization/login/OrganizationAuthenticator.java, components/org.wso2.carbon.identity.application.authenticator.organization.login/src/main/java/org/wso2/carbon/identity/application/authenticator/organization/login/constant/AuthenticatorConstants.java, pom.xml
Reverts wso2-extensions/identity-auth-organization-login#18
=> Revert "Add support to apply parent organization's URL branding to sub organizations"

components/org.wso2.carbon.identity.application.authenticator.organization.login/src/main/java/org/wso2/carbon/identity/application/authenticator/organization/login/OrganizationAuthenticator.java, components/org.wso2.carbon.identity.application.authenticator.organization.login/src/test/java/org/wso2/carbon/identity/application/authenticator/organization/login/OrganizationAuthenticatorTest.java
Pass the requested scopes of the application to child organization's authorization request
=> Pass the requested scopes of initial request  to child organization

components/org.wso2.carbon.identity.application.authenticator.organization.login/src/main/java/org/wso2/carbon/identity/application/authenticator/organization/login/OrganizationAuthenticator.java, components/org.wso2.carbon.identity.application.authenticator.organization.login/src/main/java/org/wso2/carbon/identity/application/authenticator/organization/login/constant/AuthenticatorConstants.java
- Add approles as a default claim
- Check for organization Id in request attributes
=> Check for organization Id in request attributes

components/org.wso2.carbon.identity.application.authenticator.organization.login/pom.xml, components/org.wso2.carbon.identity.application.authenticator.organization.login/src/main/java/org/wso2/carbon/identity/application/authenticator/organization/login/OrganizationAuthenticator.java, components/org.wso2.carbon.identity.application.authenticator.organization.login/src/main/java/org/wso2/carbon/identity/application/authenticator/organization/login/constant/AuthenticatorConstants.java, pom.xml
> Perform logout when OIDC logout URL is configured in the Organization Login Authenticator.
> Fix the logout issue in Organization Login Authenticator.
=> Fix federated OIDC logout issue in organization login

components/org.wso2.carbon.identity.application.authenticator.organization.login/src/main/java/org/wso2/carbon/identity/application/authenticator/organization/login/OrganizationAuthenticator.java, components/org.wso2.carbon.identity.application.authenticator.organization.login/src/main/java/org/wso2/carbon/identity/application/authenticator/organization/login/constant/AuthenticatorConstants.java
=> Update logout logic to build the logout URL in the authenticator

.github/workflows/pr-builder.yml, features/etc/feature.properties, features/org.wso2.carbon.identity.auth.organization.login.server.feature/pom.xml, pom.xml
> The organization login authenticator is exposed as feature to be added as a plugin for the carbon based middleware. The WSO2 Identity server can add this authenticator as a feature if required.
=> Add features module for organization login

components/org.wso2.carbon.identity.application.authenticator.organization.login/pom.xml, components/org.wso2.carbon.identity.application.authenticator.organization.login/src/main/java/org/wso2/carbon/identity/application/authenticator/organization/login/OrganizationAuthenticator.java, components/org.wso2.carbon.identity.application.authenticator.organization.login/src/main/java/org/wso2/carbon/identity/application/authenticator/organization/login/constant/AuthenticatorConstants.java, components/org.wso2.carbon.identity.application.authenticator.organization.login/src/main/java/org/wso2/carbon/identity/application/authenticator/organization/login/internal/AuthenticatorDataHolder.java, components/org.wso2.carbon.identity.application.authenticator.organization.login/src/main/java/org/wso2/carbon/identity/application/authenticator/organization/login/internal/AuthenticatorServiceComponent.java, components/org.wso2.carbon.identity.application.authenticator.organization.login/src/test/java/org/wso2/carbon/identity/application/authenticator/organization/login/OrganizationAuthenticatorTest.java, pom.xml
>Added support to requesting Claims using the "claims" Request Parameter
fixes -
- https://github.com/wso2/product-is/issues/16910
=> Add support to requesting Claims using the "claims" Request Parameter

components/org.wso2.carbon.identity.application.authenticator.organization.login/pom.xml, components/org.wso2.carbon.identity.application.authenticator.organization.login/src/main/java/org/wso2/carbon/identity/application/authenticator/organization/login/OrganizationAuthenticator.java, components/org.wso2.carbon.identity.application.authenticator.organization.login/src/main/java/org/wso2/carbon/identity/application/authenticator/organization/login/constant/AuthenticatorConstants.java, components/org.wso2.carbon.identity.application.authenticator.organization.login/src/main/java/org/wso2/carbon/identity/application/authenticator/organization/login/internal/AuthenticatorDataHolder.java, components/org.wso2.carbon.identity.application.authenticator.organization.login/src/main/java/org/wso2/carbon/identity/application/authenticator/organization/login/internal/AuthenticatorServiceComponent.java, components/org.wso2.carbon.identity.application.authenticator.organization.login/src/test/java/org/wso2/carbon/identity/application/authenticator/organization/login/OrganizationAuthenticatorTest.java, pom.xml
Issue https://github.com/wso2/product-is/issues/16379
=> Add organization discovery support for b2b login flow

pom.xml
=> Change identity.outbound.auth.oidc.import.version.range.

components/org.wso2.carbon.identity.application.authenticator.organization.login/pom.xml, components/org.wso2.carbon.identity.application.authenticator.organization.login/src/main/java/org/wso2/carbon/identity/application/authenticator/organization/login/OrganizationAuthenticator.java, pom.xml
$Subject
Fx for the second issue of https://github.com/wso2/product-is/issues/19668
=> Fix not adding response_mode=direct param into redirect URL generated for suborg api based auth flow

components/org.wso2.carbon.identity.application.authenticator.organization.login/pom.xml, components/org.wso2.carbon.identity.application.authenticator.organization.login/src/test/java/org/wso2/carbon/identity/application/authenticator/organization/login/OrganizationAuthenticatorTest.java, pom.xml
=> Bump auth oidc version and fix test failures

components/org.wso2.carbon.identity.application.authenticator.organization.login/src/main/java/org/wso2/carbon/identity/application/authenticator/organization/login/OrganizationAuthenticator.java, pom.xml
Fix wrong callback url usage in API based auth in B2B login flow
Part of the first issue of https://github.com/wso2/product-is/issues/19668
- Depends on https://github.com/wso2-extensions/identity-outbound-auth-oidc/pull/173
=> Fix wrong callback url usage in API based auth

components/org.wso2.carbon.identity.application.authenticator.organization.login/pom.xml, components/org.wso2.carbon.identity.application.authenticator.organization.login/src/main/java/org/wso2/carbon/identity/application/authenticator/organization/login/OrganizationAuthenticator.java
- Add missing import packages.
- Add SP name to saml post page.
- https://github.com/wso2/product-is/issues/20159
- https://github.com/wso2-extensions/identity-auth-organization-login/pull/39
=> Add Missing Import Packages

components/org.wso2.carbon.identity.application.authenticator.organization.login/src/main/java/org/wso2/carbon/identity/application/authenticator/organization/login/OrganizationAuthenticator.java, components/org.wso2.carbon.identity.application.authenticator.organization.login/src/test/java/org/wso2/carbon/identity/application/authenticator/organization/login/OrganizationAuthenticatorTest.java, pom.xml
>  $subject
- https://github.com/wso2/product-is/issues/20324
=> Get oauth app using client and shared org tenant domain

.github/workflows/pr-builder.yml, codecov.yml
=> Add codecov configs

components/org.wso2.carbon.identity.application.authenticator.organization.login/src/main/java/org/wso2/carbon/identity/application/authenticator/organization/login/OrganizationAuthenticator.java
- $Subject
- https://github.com/wso2/product-is/issues/20953
- https://github.com/wso2/identity-apps/pull/6805
- https://github.com/wso2-extensions/identity-auth-organization-login/pull/45
=> Update Invalid Org Discovery Type Error to be Consistent with i18n Keys

components/org.wso2.carbon.identity.application.authenticator.organization.login/pom.xml, components/org.wso2.carbon.identity.application.authenticator.organization.login/src/main/java/org/wso2/carbon/identity/application/authenticator/organization/login/OrganizationAuthenticator.java, components/org.wso2.carbon.identity.application.authenticator.organization.login/src/main/java/org/wso2/carbon/identity/application/authenticator/organization/login/internal/AuthenticatorDataHolder.java, components/org.wso2.carbon.identity.application.authenticator.organization.login/src/main/java/org/wso2/carbon/identity/application/authenticator/organization/login/internal/AuthenticatorServiceComponent.java, components/org.wso2.carbon.identity.application.authenticator.organization.login/src/test/java/org/wso2/carbon/identity/application/authenticator/organization/login/OrganizationAuthenticatorTest.java
> $Subject
- https://github.com/wso2-extensions/identity-outbound-auth-oidc/pull/177
- https://github.com/wso2-extensions/identity-auth-organization-login/pull/39
- https://github.com/wso2-extensions/identity-auth-organization-login/pull/40
=> Add Default Branding to SAML Redirection Page for SAML IdP  Initiate B2B Login Flows

.github/workflows/pr-builder.yml, components/org.wso2.carbon.identity.application.authenticator.organization.login/src/main/java/org/wso2/carbon/identity/application/authenticator/organization/login/OrganizationAuthenticator.java, pom.xml
This PR must be merged after https://github.com/wso2-extensions/identity-organization-management/pull/489 as the organization discovery component version needs to be bumped.
Updates the organization discovery flow to include the authentication context.
- https://github.com/wso2/product-is/issues/23390
- https://github.com/wso2-extensions/identity-organization-management/pull/489
=> Update organization discovery to include the authentication context

components/org.wso2.carbon.identity.application.authenticator.organization.login/src/main/java/org/wso2/carbon/identity/application/authenticator/organization/login/OrganizationAuthenticator.java
Currently, we don't have an option to pass additional query params in the authorize request to sub organizations. This PR adds the support to pass additional query params in the authorize request to sub organization via adaptive script. With this improvements, additional query params can be sent as a authenticator param in adaptive script. 
Query param values have following options,
1. Static values. (Eg: `param=sampleValue`)
2. Dynamic request params passed as query param or body param in initial authorize request. (Eg: `param=${requestParam}`)
3. Dynamic auth params passed via adaptive script. (Eg: `param=$authparam{param}`)
Issue - https://github.com/wso2/product-is/issues/23574
=> Add support for additional query params via adaptive script

components/org.wso2.carbon.identity.application.authenticator.organization.login/src/main/java/org/wso2/carbon/identity/application/authenticator/organization/login/OrganizationAuthenticator.java
$subject
The fix is to set the skipDomainBranding flag as true in the OIDC logout URL and Callback URL in the Logout flow.
For the callback URL, previously a value was not explicitly set and the default value was taken in the OpenIDConnectAuthenticator[1]
[1] https://github.com/wso2-extensions/identity-outbound-auth-oidc/blob/08d61dee1ef6d8675fe462c8344d7bb91124e1a6/components/org.wso2.carbon.identity.application.authenticator.oidc/src/main/java/org/wso2/carbon/identity/application/authenticator/oidc/OpenIDConnectAuthenticator.java#L312
- https://github.com/wso2/carbon-identity-framework/pull/5700
- https://github.com/wso2/carbon-identity-framework/pull/5725
- https://github.com/wso2/carbon-identity-framework/pull/5752
- https://github.com/wso2-extensions/identity-inbound-auth-oauth/pull/2 …
=> Fix issue in logout flow for custom domains

components/org.wso2.carbon.identity.application.authenticator.organization.login/pom.xml, components/org.wso2.carbon.identity.application.authenticator.organization.login/src/main/java/org/wso2/carbon/identity/application/authenticator/organization/login/OrganizationAuthenticator.java, components/org.wso2.carbon.identity.application.authenticator.organization.login/src/main/java/org/wso2/carbon/identity/application/authenticator/organization/login/constant/AuthenticatorConstants.java, components/org.wso2.carbon.identity.application.authenticator.organization.login/src/test/java/org/wso2/carbon/identity/application/authenticator/organization/login/OrganizationAuthenticatorTest.java, pom.xml
$subject
Issues: https://github.com/wso2/product-is/issues/23526
Related PRs:
- https://github.com/wso2/identity-apps/pull/8249
- https://github.com/wso2-extensions/identity-organization-management/pull/517
- https://github.com/wso2/identity-api-server/pull/904
- https://github.com/wso2/identity-organization-management-core/pull/183
=> Add organization handle discovery support for b2b login flow
